/**
 * src/exporters/github/index.ts
 *
 * Export Adapter — GitHub Issues JSON (Part 8.2 — Addition 8)
 *
 * Converts a Blueprint's implementation tasks into a GitHub Issues bulk-import
 * JSON array. Each section becomes a set of issues under a single epic.
 *
 * Usage: POST /api/v1/blueprints/:id/export-action with { format: "github" }
 */

import type { Blueprint } from '../../engine/types';

export interface GitHubIssue {
  title: string;
  body: string;
  labels: string[];
  milestone?: string;
  assignees: string[];
  state: 'open';
}

export interface GitHubExportResult {
  repository?: string;
  milestone: string;
  issues: GitHubIssue[];
  totalIssues: number;
  exportedAt: string;
}

const SECTION_LABEL_MAP: Record<string, string[]> = {
  executive_summary: ['documentation', 'overview'],
  architecture:      ['architecture', 'design'],
  data_model:        ['database', 'backend'],
  api_contracts:     ['api', 'backend'],
  security_model:    ['security'],
  edge_cases:        ['reliability', 'testing'],
  testing_strategy:  ['testing', 'quality'],
  deployment:        ['devops', 'deployment'],
  launch_checklist:  ['release', 'devops'],
  technical_debt:    ['tech-debt', 'maintenance'],
};

function extractTasks(content: string, limit = 20): string[] {
  const tasks: string[] = [];
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (/^(-\s*\[[ x]\]|[\d]+\.|[•*-])\s+/.test(trimmed)) {
      const task = trimmed.replace(/^(-\s*\[[ x]\]|[\d]+\.|[•*-])\s+/, '').trim();
      if (task.length > 10 && task.length < 200) tasks.push(task);
    }
  }
  return tasks.slice(0, limit);
}

function buildIssueBody(task: string, context: string, blueprintId: string, section: string): string {
  return `## Task

${task}

## Context

> Blueprint: \`${blueprintId}\` — ${section}

${context.slice(0, 800)}${context.length > 800 ? '\n\n_[See full blueprint for complete context]_' : ''}

## Acceptance Criteria

- [ ] Implementation matches the blueprint specification
- [ ] Unit tests written and passing
- [ ] Code review completed

## References

- Blueprint ID: \`${blueprintId}\`
- Section: ${section}
- Generated by [Atomic](https://github.com/atomic-blueprint/atomic)
`;
}

/**
 * Export a Blueprint as a GitHub Issues bulk-import JSON array.
 */
export function exportToGitHubIssues(
  blueprint: Blueprint,
  blueprintId: string,
  opts: { repository?: string; milestone?: string; labels?: string[] } = {},
): GitHubExportResult {
  const appName = blueprint.intent?.product_name ?? 'Blueprint';
  const milestone = opts.milestone ?? appName ?? 'v1.0.0';
  const baseLabels = ['atomic-generated', ...(opts.labels ?? [])];
  const issues: GitHubIssue[] = [];

  // Epic: tracks the whole blueprint
  issues.push({
    title: `[EPIC] ${appName} — Full Implementation`,
    body: `## Blueprint Overview

**App**: ${appName}
**Domain**: ${blueprint.intent?.domain ?? 'N/A'}
**Quality Score**: ${blueprint.quality_score ?? 'N/A'}/100

## Architecture Summary

${blueprint.sections.executive_summary?.slice(0, 1000) ?? 'See blueprint for full overview.'}

---
_Generated by [Atomic](https://github.com/atomic-blueprint/atomic) · Blueprint ID: \`${blueprintId}\`_
`,
    labels: [...baseLabels, 'epic', 'architecture'],
    milestone,
    assignees: [],
    state: 'open',
  });

  // Issues from each blueprint section
  for (const [key, content] of Object.entries(blueprint.sections)) {
    if (!content || typeof content !== 'string') continue;
    const sectionTitle = key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
    const labels = [...baseLabels, ...(SECTION_LABEL_MAP[key] ?? ['feature'])];
    const tasks = extractTasks(content);

    if (tasks.length === 0) {
      issues.push({
        title: `Implement ${sectionTitle}`,
        body: buildIssueBody(`Implement ${sectionTitle}`, content, blueprintId, sectionTitle),
        labels,
        milestone,
        assignees: [],
        state: 'open',
      });
    } else {
      for (const task of tasks) {
        issues.push({
          title: task.length > 100 ? task.slice(0, 97) + '...' : task,
          body: buildIssueBody(task, content.slice(0, 600), blueprintId, sectionTitle),
          labels,
          milestone,
          assignees: [],
          state: 'open',
        });
      }
    }
  }

  // Issues from pillar decisions
  for (const [, pillar] of Object.entries(blueprint.pillars)) {
    const pillarTitle = pillar.pillar.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
    for (const decision of (pillar.summary?.decisions ?? []).slice(0, 5)) {
      issues.push({
        title: `[${pillarTitle}] ${decision.feature ?? 'Implementation task'}`,
        body: `## Architectural Decision\n\n**Feature**: ${decision.feature}\n**Rationale**: ${decision.rationale}\n\n---\nBlueprint ID: \`${blueprintId}\``,
        labels: [...baseLabels, 'architecture', pillar.pillar.replace(/_/g, '-')],
        milestone,
        assignees: [],
        state: 'open',
      });
    }
  }

  return {
    repository: opts.repository,
    milestone,
    issues,
    totalIssues: issues.length,
    exportedAt: new Date().toISOString(),
  };
}
