/**
 * src/exporters/notion/index.ts
 *
 * Export Adapter — Notion Page JSON (Part 8.2 — Addition 8)
 *
 * Usage: POST /api/v1/blueprints/:id/export-action with { format: "notion" }
 */

import type { Blueprint, BlueprintSections } from '../../engine/types';

interface NotionRichText {
  type: 'text';
  text: { content: string };
  annotations?: { bold?: boolean; italic?: boolean; code?: boolean };
}

interface NotionBlock {
  object: 'block';
  type: string;
  [key: string]: unknown;
}

export interface NotionExportResult {
  title: string;
  blocks: NotionBlock[];
  totalBlocks: number;
  exportedAt: string;
  importInstructions: string;
}

function rt(content: string, opts: NotionRichText['annotations'] = {}): NotionRichText {
  return {
    type: 'text',
    text: { content },
    annotations: Object.keys(opts).length > 0 ? opts : undefined,
  };
}

function heading1(text: string): NotionBlock {
  return { object: 'block', type: 'heading_1', heading_1: { rich_text: [rt(text)] } };
}

function heading2(text: string): NotionBlock {
  return { object: 'block', type: 'heading_2', heading_2: { rich_text: [rt(text)] } };
}

function heading3(text: string): NotionBlock {
  return { object: 'block', type: 'heading_3', heading_3: { rich_text: [rt(text)] } };
}

function paragraph(text: string): NotionBlock {
  return { object: 'block', type: 'paragraph', paragraph: { rich_text: [rt(text.slice(0, 1900))] } };
}

function callout(text: string, emoji = '💡'): NotionBlock {
  return {
    object: 'block',
    type: 'callout',
    callout: {
      rich_text: [rt(text.slice(0, 1900))],
      icon: { type: 'emoji', emoji },
      color: 'blue_background',
    },
  };
}

function divider(): NotionBlock {
  return { object: 'block', type: 'divider', divider: {} };
}

function bulletItem(text: string): NotionBlock {
  return {
    object: 'block',
    type: 'bulleted_list_item',
    bulleted_list_item: { rich_text: [rt(text.slice(0, 1900))] },
  };
}

function tableOfContents(): NotionBlock {
  return { object: 'block', type: 'table_of_contents', table_of_contents: { color: 'default' } };
}

function sectionToBlocks(title: string, content: string, maxChars = 2000): NotionBlock[] {
  if (!content || content.length < 10) return [];
  const blocks: NotionBlock[] = [heading2(title)];
  let totalChars = 0;

  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    if (trimmed.startsWith('### ')) blocks.push(heading3(trimmed.replace(/^### /, '')));
    else if (trimmed.startsWith('## ')) blocks.push(heading3(trimmed.replace(/^## /, '')));
    else if (trimmed.startsWith('# ')) blocks.push(heading3(trimmed.replace(/^# /, '')));
    else if (/^[-*•]\s+/.test(trimmed)) blocks.push(bulletItem(trimmed.replace(/^[-*•]\s+/, '')));
    else blocks.push(paragraph(trimmed));

    totalChars += trimmed.length;
    if (totalChars >= maxChars) {
      blocks.push(paragraph('_[Content truncated — see full blueprint for complete details]_'));
      break;
    }
  }
  blocks.push(divider());
  return blocks;
}

const SECTION_ORDER: Array<[keyof BlueprintSections, string]> = [
  ['executive_summary', '🗺️ Executive Summary'],
  ['architecture',      '🏗️ Architecture'],
  ['api_contracts',     '🔌 API Contracts'],
  ['data_model',        '🗄️ Data Model'],
  ['security_model',    '🔒 Security Model'],
  ['edge_cases',        '⚡ Edge Cases'],
  ['testing_strategy',  '🧪 Testing Strategy'],
  ['deployment',        '🚀 Deployment'],
  ['launch_checklist',  '✅ Launch Checklist'],
  ['technical_debt',    '🔧 Technical Debt'],
];

/**
 * Export a Blueprint as a Notion page block array.
 */
export function exportToNotionPage(
  blueprint: Blueprint,
  blueprintId: string,
): NotionExportResult {
  const appName = blueprint.intent?.product_name ?? 'Blueprint';
  const blocks: NotionBlock[] = [];

  blocks.push(callout(
    `Generated by Atomic · Blueprint ID: ${blueprintId} · Quality: ${blueprint.quality_score ?? 'N/A'}/100 · ${new Date().toLocaleDateString()}`,
    '🤖',
  ));
  blocks.push(tableOfContents());
  blocks.push(divider());

  // Pillar decisions
  if (Object.keys(blueprint.pillars).length > 0) {
    blocks.push(heading1('🏛️ Architecture Pillars'));
    for (const pillar of Object.values(blueprint.pillars)) {
      const pillarTitle = pillar.pillar.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
      blocks.push(heading2(pillarTitle));

      for (const d of (pillar.summary?.decisions ?? []).slice(0, 6)) {
        blocks.push(bulletItem(`${d.feature}: ${d.rationale}`));
      }
      for (const c of (pillar.summary?.technical_constraints ?? []).slice(0, 4)) {
        blocks.push(bulletItem(String(c)));
      }
      blocks.push(divider());
    }
  }

  // Sections in canonical order
  blocks.push(heading1('📄 Implementation Specification'));
  for (const [key, title] of SECTION_ORDER) {
    const content = blueprint.sections[key];
    if (content) blocks.push(...sectionToBlocks(title, content, 3000));
  }

  // Metadata
  blocks.push(heading1('📊 Blueprint Metadata'));
  blocks.push(bulletItem(`Blueprint ID: ${blueprintId}`));
  blocks.push(bulletItem(`Quality Score: ${blueprint.quality_score ?? 'N/A'}/100`));
  blocks.push(bulletItem(`Generated: ${new Date().toISOString()}`));
  blocks.push(bulletItem(`App: ${appName}`));
  blocks.push(bulletItem(`Pillars: ${Object.keys(blueprint.pillars).join(', ')}`));

  return {
    title: `${appName} — Atomic Blueprint`,
    blocks,
    totalBlocks: blocks.length,
    exportedAt: new Date().toISOString(),
    importInstructions: `Use the Notion API (pages.create with children: blocks) to import this ${blocks.length}-block page. Blueprint ID: ${blueprintId}`,
  };
}
