/**
 * src/exporters/claude-md/index.ts
 *
 * Export Adapter — Auto-generate CLAUDE.md from a Blueprint (Part 8.2 — Addition 8)
 *
 * Usage: POST /api/v1/blueprints/:id/export-action with { format: "claude-md" }
 */

import type { Blueprint, BlueprintSections } from '../../engine/types';

export interface ClaudeMdExportResult {
  markdown: string;
  wordCount: number;
  exportedAt: string;
}

function getSection(sections: BlueprintSections, ...keys: (keyof BlueprintSections)[]): string {
  for (const key of keys) {
    const v = sections[key];
    if (v && v.trim().length > 50) return v.trim();
  }
  return '_Not specified in blueprint._';
}

function pillarDecisionsList(blueprint: Blueprint, pillarName: string): string {
  const pillar = Object.values(blueprint.pillars).find(p => p.pillar === pillarName);
  if (!pillar?.summary?.decisions?.length) return '';
  return pillar.summary.decisions
    .slice(0, 10)
    .map(d => `- **${d.feature}**: ${d.rationale}`)
    .join('\n');
}

/**
 * Generate a CLAUDE.md for this blueprint.
 */
export function exportToClaudeMd(
  blueprint: Blueprint,
  blueprintId: string,
  opts: { includeRawSections?: boolean } = {},
): ClaudeMdExportResult {
  const appName = blueprint.intent?.product_name ?? 'Project';
  const domain = blueprint.intent?.domain ?? '';
  const problem = blueprint.intent?.core_problem ?? '';
  const s = blueprint.sections;

  const architecture = getSection(s, 'architecture');
  const api = getSection(s, 'api_contracts');
  const database = getSection(s, 'data_model');
  const security = getSection(s, 'security_model');
  const testing = getSection(s, 'testing_strategy');
  const deployment = getSection(s, 'deployment');
  const overview = getSection(s, 'executive_summary');

  const securityDecisions = pillarDecisionsList(blueprint, 'security');
  const productionDecisions = pillarDecisionsList(blueprint, 'production');

  const markdown = `# ${appName}

> Generated by [Atomic](https://github.com/atomic-blueprint/atomic) · Blueprint ID: \`${blueprintId}\`
> Quality Score: ${blueprint.quality_score ?? 'N/A'}/100 · Generated: ${new Date().toISOString().split('T')[0]}

## Project Overview

${problem}

${domain ? `**Domain**: ${domain}` : ''}

---

## Executive Summary

${overview.slice(0, 1500)}${overview.length > 1500 ? '\n\n_[Truncated — see full blueprint]_' : ''}

---

## Key Commands

\`\`\`bash
# Development
npm run dev        # Start development server
npm run build      # Production build
npm run typecheck  # TypeScript type check

# Testing
npm test           # Run test suite
npm run test:e2e   # End-to-end tests

# Database
npm run db:migrate    # Run pending migrations
npm run db:rollback   # Rollback last migration
\`\`\`

---

## Architecture

${architecture.slice(0, 2000)}${architecture.length > 2000 ? '\n\n_[See full blueprint for complete architecture]_' : ''}

---

## API Design

${api.slice(0, 1500)}${api.length > 1500 ? '\n\n_[See full blueprint for complete API specification]_' : ''}

---

## Data Model

${database.slice(0, 1500)}${database.length > 1500 ? '\n\n_[See full blueprint for complete data model]_' : ''}

---

## Security Requirements

${securityDecisions ? securityDecisions + '\n\n' : ''}${security.slice(0, 1000)}${security.length > 1000 ? '\n\n_[See full blueprint for complete security specification]_' : ''}

---

## Production Architecture

${productionDecisions ? productionDecisions + '\n\n' : ''}

---

## Testing Strategy

${testing.slice(0, 1000)}${testing.length > 1000 ? '\n\n_[See full blueprint for complete test strategy]_' : ''}

---

## Deployment

${deployment.slice(0, 800)}${deployment.length > 800 ? '\n\n_[See full blueprint for complete deployment specification]_' : ''}

---

## Implementation Notes

### Coding Conventions

- Follow existing patterns; do not introduce new conventions without documenting them
- Every new function must have JSDoc comments
- All TypeScript types must be strict (no \`any\` unless explicitly justified)
- Validate all external inputs before processing
- Never log PII or secrets

### Agent Guidelines

When implementing features from this blueprint:
1. Read the relevant section before writing code
2. Implement one component at a time; verify it works before moving to the next
3. Write tests alongside implementation (not after)
4. Flag any contradictions between sections as comments in the code

### What Claude Code Should NOT Do

- Do NOT change the tech stack without flagging it as a breaking change
- Do NOT skip error handling or logging
- Do NOT commit secrets, API keys, or passwords
- Do NOT modify production database schema without a migration script
- Do NOT remove existing tests

---

${opts.includeRawSections ? `## Raw Blueprint Sections\n\n${Object.entries(s).map(([k, v]) => `### ${k}\n\n${String(v).slice(0, 500) ?? 'N/A'}`).join('\n\n---\n\n')}\n\n---\n\n` : ''}

_This CLAUDE.md was auto-generated from the Atomic blueprint. Update it as the implementation evolves._
`;

  return {
    markdown: markdown.trim(),
    wordCount: markdown.split(/\s+/).length,
    exportedAt: new Date().toISOString(),
  };
}
