/**
 * src/sdk/resources/artemis.ts
 *
 * Artemis resource — pre-pipeline scoping agent session management.
 */

import type { AtomicHTTP } from '../client';
import type {
  ArtemisSession, ArtemisWorkspace, ArtemisChatOptions, ArtemisChatResult,
} from '../types';

export class ArtemisResource {
  constructor(private readonly http: AtomicHTTP) {}

  /**
   * Create a new Artemis session for project scoping.
   *
   * @example
   * ```ts
   * const session = await client.artemis.createSession();
   * // Now chat with Artemis to define the project
   * const result = await client.artemis.chat({
   *   sessionId: session.sessionId,
   *   message:   "I'm building a food-delivery SaaS",
   *   onChunk:   chunk => process.stdout.write(chunk),
   * });
   * ```
   */
  async createSession(config?: Record<string, unknown>): Promise<ArtemisSession> {
    // Server returns { sessionId, workspace }; normalize to an ArtemisSession
    const result = await this.http.request<{ sessionId?: string; workspace?: ArtemisWorkspace } & Partial<ArtemisSession>>('/artemis/session', {
      method: 'POST',
      body:   { config },
    });
    if (result.sessionId && result.workspace) {
      return { sessionId: result.sessionId, workspace: result.workspace };
    }
    return result as unknown as ArtemisSession;
  }

  /** Get the current Artemis workspace for a session (includes brief + confidence) */
  async getWorkspace(sessionId: string): Promise<ArtemisWorkspace> {
    const res = await this.http.request<{ workspace: ArtemisWorkspace }>(
      `/artemis/${sessionId}/workspace`,
    );
    return res.workspace;
  }

  /**
   * Send a message to Artemis and stream the response.
   * Resolves to the full response + updated workspace once streaming completes.
   */
  async chat(opts: ArtemisChatOptions): Promise<ArtemisChatResult> {
    const { sessionId, message, activeSkillIds = [], onChunk } = opts;

    let content = '';
    await this.http.stream(
      `/artemis/${sessionId}/chat`,
      { message, activeSkillIds },
      chunk => {
        content += chunk;
        onChunk?.(chunk);
      },
    );

    const workspace = await this.getWorkspace(sessionId);
    return { content, workspace };
  }

  /**
   * Approve the Project Brief generated by Artemis.
   * Must be called before triggering the pipeline.
   * Returns the final confidence score and brief.
   */
  async approveBrief(sessionId: string): Promise<{ approved: boolean; workspace: ArtemisWorkspace }> {
    const res = await this.http.request<{ approved: boolean }>(`/artemis/${sessionId}/approve`, {
      method: 'POST',
    });
    const workspace = await this.getWorkspace(sessionId);
    return { ...res, workspace };
  }

  /**
   * Delete an Artemis session and its associated state.
   */
  async deleteSession(sessionId: string): Promise<{ deleted: boolean }> {
    return this.http.request<{ deleted: boolean }>(`/artemis/${sessionId}`, {
      method: 'DELETE',
    });
  }
}
