/**
 * src/plugins/built-in/export-markdown.ts
 *
 * Built-in export plugin — exports blueprint as a rich, structured Markdown document.
 */

import type { PluginDefinition, ExportPlugin } from '../types';
import type { Blueprint } from '../../sdk/types';

const SECTION_LABELS: Record<string, string> = {
  executive_summary: 'Executive Summary',
  architecture:      'System Architecture',
  data_model:        'Data Model',
  api_contracts:     'API Contracts',
  security_model:    'Security Model',
  edge_cases:        'Edge Cases',
  testing_strategy:  'Testing Strategy',
  deployment:        'Deployment',
  launch_checklist:  'Launch Checklist',
  technical_debt:    'Technical Debt',
};

function blueprintToMarkdown(blueprint: Blueprint): string {
  const lines: string[] = [];
  const name = blueprint.intent?.product_name ?? 'Blueprint';
  const date = new Date(blueprint.created_at).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  lines.push(`# ${name}`);
  lines.push(`> Generated by Atomic — ${date}`);
  lines.push('');
  lines.push(`**Quality Score:** ${blueprint.quality_score}/100`);
  lines.push(`**Mode:** ${blueprint.mode}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Sections
  for (const [key, label] of Object.entries(SECTION_LABELS)) {
    const content = blueprint.sections[key];
    if (!content) continue;
    lines.push(`## ${label}`);
    lines.push('');
    lines.push(content.trim());
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Pillars
  if (blueprint.pillars && Object.keys(blueprint.pillars).length > 0) {
    lines.push('## Pillar Analysis');
    lines.push('');
    for (const [pillarKey, pillar] of Object.entries(blueprint.pillars)) {
      lines.push(`### ${pillar.name ?? pillarKey}`);
      lines.push('');
      for (const agent of pillar.agents ?? []) {
        lines.push(`#### ${agent.agent}`);
        lines.push('');
        lines.push(agent.content ?? '');
        lines.push('');
      }
    }
  }

  lines.push('---');
  lines.push(`*Generated by [Atomic](https://atomic.dev) · Blueprint ID: ${blueprint.id}*`);

  return lines.join('\n');
}

const plugin: ExportPlugin = {
  type:        'export',
  exportLabel: 'Export as Markdown',
  exportMime:  'text/markdown',
  exportExt:   'md',

  execute(blueprint: Blueprint) {
    return blueprintToMarkdown(blueprint);
  },
};

export const exportMarkdownPlugin: PluginDefinition<ExportPlugin> = {
  manifest: {
    id:          'built-in/export-markdown',
    name:        'Markdown Export',
    description: 'Export the blueprint as a rich, structured Markdown document',
    version:     '1.0.0',
    author:      'Atomic',
    category:    'export',
    icon:        'FileText',
    permissions: ['blueprint:read'],
  },
  plugin,
};
